services:
  db:
    image: postgres:16.3
    container_name: quest_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quests
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
# Access on port 5431
volumes:
  db-data:
